imports:
    - { resource: parameters.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/cms_config.yml }

    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_product.yml }
    - { resource: sonata/sonata_formatter.yml }
    #- { resource: sonata/sonata_news.yml }
    - { resource: initcms/initcms.yml }


framework:
    #esi:             ~
    translator:      { fallback: 'it'}
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:            false

mopa_bootstrap:
    menu: ~
    icons:
        icon_set: fontawesome4
        shortcut: icon
    
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        lessphp:
            #file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php # use with leafo/lessphp - not supporting bootstrap 3.1
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php # use with oyejorge/less.php
            apply_to: "\.less$"
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
        sass:
            bin: d:\Programmi\Ruby21\bin\sass
            apply_to: "\.sass$"
        scss:
            bin: d:\Programmi\Ruby21\bin\scss
            apply_to: "\.scss$"
        compass:
            bin: d:\Programmi\Ruby21\bin\compass
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
            currency: Sonata\Component\Currency\CurrencyDoctrineType
        mapping_types:
            enum: string


    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                auto_mapping:     true
                connection:       default
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    #ApplicationNetworkingInitCmsBundle: ~
                    ApplicationSonataProductBundle: ~
                    SonataProductBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    #SonataClassificationBundle: ~
                    SonataMediaBundle: 
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_sortable:
                        type: annotation
                        prefix: Gedmo\Sortable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
                        alias: GedmoSortable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    FOSUserBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

lexik_translation:
    fallback_locale: it      # (required) default locale to use
    managed_locales: [it, en]    # (required) locales that the bundle have to manage

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name:  main
    user_class:     Application\Networking\InitCmsBundle\Entity\User
    group:
        group_class: Networking\InitCmsBundle\Entity\Group
    from_email:
            address:        webmaster@example.com
            sender_name:    net working Team

