parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     initcms
    database_user:     initcms
    database_password: initcms
    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    locale:            it_IT
    secret:            Liejrgp<@4>twnmae.ogaisygfnk<4g_us<4fghw4i

    main_email_address:       info@lerocchemalatestiane.it
    main_email_sender_name:   Le Rocche Malatestiane

    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time