# 
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        "news"
    link:         "news"
    description:  "news"
    salt:         framework.secret

    admin:
        post:       
            class:  Application\Sonata\NewsBundle\Admin\PostAdmin

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    class:
#        tag:        Application\Sonata\ClassificationBundle\Entity\Tag
#        collection: Application\Sonata\ClassificationBundle\Entity\Collection
        post:       Application\Sonata\NewsBundle\Entity\Post
#        comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Networking\InitCmsBundle\Entity\Media
        user:       Application\Networking\InitCmsBundle\Entity\User

    # comment options
    comment:
        notification:
            emails:   [%main_email_address%]
            from:     %main_email_sender_name%
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~