sonata_admin:
    title:      Rocche Malatestiane
    title_logo: /bundles/applicationnetworkinginitcms/img/logo_color.png
    options:
        use_select2: false
        
    dashboard:
        blocks:
            - { position: top, type: networking_init_cms.block.service.translatable_text, settings: { translation_key: "info.welcome_text", translation_domain: 'NetworkingInitCmsBundle'} }
            - { position: left, type: networking_init_cms.block.service.pages}
            - { position: right, type: networking_init_cms.block.service.online_users}

        groups:
            products:
                label: "products.admin_menu_label"
                items: [sonata.product.admin.product]
#            pages:
#                label: "pages.admin_menu_label"
#                items: [networking_init_cms.admin.page]
#            menu:
#                label: "menu.admin_menu_label"
#                items: [ networking_init_cms.admin.menu_item]
#            media:
#                label: "sonata_media.admin_menu_label"
#                items: [sonata.media.admin.media, sonata.media.admin.gallery, networking_init_cms.admin.tag]
#            users:
#                label: "sonata_user"
#                items: [sonata.user.admin.user, sonata.user.admin.group]
#            help_text:
#                label: "help_text.admin_menu_label"
#                items: [networking_init_cms.admin.help_text]
#            translation:
#                label: "translation.admin_menu_label"
#                items: [ibrows_sonata_translation.admin.orm]