sonata_classification:
    class:
        tag:          Application\Sonata\ClassificationBundle\Entity\Tag
        category:     Application\Sonata\ClassificationBundle\Entity\Category
        collection:   Application\Sonata\ClassificationBundle\Entity\Collection
        media:        Networking\InitCmsBundle\Entity\Media
        
    admin:
        collection:
            class:        ApplicationUODDA\Sonata\ClassificationBundle\Admin\CollectionAdmin
#              controller:   SonataAdminBundle:CRUD
#              translation:  SonataClassificationBundle
#          tag:
#              class:        Sonata\ClassificationBundle\Admin\TagAdmin
#              controller:   SonataAdminBundle:CRUD
#              translation:  SonataClassificationBundle
        category:
            class:        ApplicationFAX\Sonata\ClassificationBundle\Admin\CategoryAdmin
#              controller:   SonataAdminBundle:CRUD
#              translation:  SonataClassificationBundle
